# Generated by Django 3.2.3 on 2025-12-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ('name',)},
        ),
    ]
